import "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\corprof.idl";

[
	object,
	uuid(FDEDE932-9F80-4CE5-891E-3B24768CFBCB),
	dual,
	helpstring("INProfCORHook Interface"),
	pointer_default(unique)
] 
#line 733 "c:\\users\\nt4-\\documents\\visual studio 2010\\projects\\loadtesting\\hook\\hook.cpp"
interface INProfCORHook : IDispatch {
};


[ version(1.0), uuid(A461E20A-C7DC-4A89-A24E-87B5E975A96B), helpstring("NProf.Hook 1.0 Type Library") ]
library NProfHook
{
	importlib("stdole2.tlb");

	[
		version(1.0),
		uuid(107F578A-E019-4BAF-86A1-7128A749DB05),
		helpstring("nprof COR Profiling Hook Class")
	] 
#line 745 "c:\\users\\nt4-\\documents\\visual studio 2010\\projects\\loadtesting\\hook\\hook.cpp"
	coclass CNProfCORHook {
		interface INProfCORHook;
	};

}

